<!DOCTYPE html>
<html>
<head>
  <title></title>

<!-- Rutas -->
<?php $loginuserpassword  = $this->url('login', ['action' => 'loginuserpassword']); ?>
<?php $urlCardNo = $this->url('login', ['action' => 'logincardnro']); ?>
<?php $pinNum = $this->url('login', ['action' => 'loginpin']); ?>
<?php $guess = $this->url('login', ['action' => 'loginguess']); ?>
<?php $loginandrelease  = $this->url('liberador', ['action' => 'loginandrelease']); ?>
<?php $liberador = $this->url('liberador', ['action' => 'cargarliberador']); ?>
<?php $panelcontrol = $this->url('paneldecontrol', ['action' => 'panel']); ?>
<?php $urlEnrolar = $this->url('login', ['action' => 'enrolar']); ?>
<?php $validarPin = $this->url('login', ['action' => 'validarPin']); ?>
<?php $asociar = $this->url('login', ['action' => 'asociarpin']); ?>
<?php $logout  = $this->url('login', ['action' => 'logout']); ?>

<style type="text/css">
  .ui-keyboard {
   margin-top: 10%;
   top: 0px;  
}

.inputOculto{
    background-color: transparent;
    border: 0px;
    outline: none;
    -webkit-box-shadow: none;
    -moz-box-shadow: none;
    box-shadow: none;
    width:5px;
    color:transparent;
    cursor:default;
}

body{
  background-image: url("<?php echo $backgroundImage ?>");
  background-color: <?php echo "#".$backgroundColor ?>;
}

<?php echo $styleBackgroundImage ?>
</style>

</head>
<body>

  <div class="row">
    <div id="alertPrinter" class="message-box danger no-padding col-xs-12 col-md-offset-2 col-md-8 fade in hidden">
        <div class="icon-box">
          <i class="fa fa-exclamation-circle fa-2x"></i>
        </div>
        <p id="printerStatusAlert" class="text-center"></p>
      </div>
  </div>
    
    <div class="row">
      <div class="message-box info no-padding col-xs-12 col-md-offset-2 col-md-8">
          <div class="icon-box">
            <i class="fa fa-info-circle fa-2x"></i>
          </div>
          <p id="mensajeFunciones"></p>
        </div>
    </div>

    <div class="row" id="wrapLogin">
      <div class=" col-xs-12 col-md-offset-1 col-md-10 col-lg-offset-3 col-lg-6">
        <div class="row-flex">
          <div class="col-flex" style="display: none;" id="pinLogin">
            <a href="#" data-toggle="modal" data-target="#modalPin" class="icon-option ico-pin">
            <!-- <img src="<?php echo $this->basePath(); ?>/img/ico-pin.png" alt="" class="img-responsive"> -->
            </a>
            <p>Ingresa tu ID</p>
          </div>
          <div class="col-flex" style="display: none;" id="tarjetaLogin">
          <form action="<?= $urlCardNo ?>" id="cardForm" method="post" autoComplete="off">
          <!-- inputInvisible -->
            <input class="inputOculto" type="password" name="cardNo" id="cardNo" onkeyup="keyUpSpeed()" maxlength="100" autoComplete="off">
          </form>
            <a href="#" data-toggle="modal" data-target="#modalTarjeta" class="icon-option ico-card">
            <!-- <img src="<?php echo $this->basePath(); ?>/img/ico-card.png" alt="" class="img-responsive"> --> 
            </a>
            <p>Desliza tu tarjeta</p>
          </div>
          <div class="col-flex" style="display: none;" id="usuarioLogin">
            <a href="#" data-toggle="modal" data-target="#modalUsuario" class="icon-option ico-user">
            <!-- <img src="<?php echo $this->basePath(); ?>/img/ico-user.png" alt="" class="img-responsive"> -->
            </a>
            <p>Usuario registrado</p>
          </div>
          <div class="col-flex" style="display: none;" id="anonimoLogin">
            <form id="guessForm" action="<?= $guess ?>" method="post" autocomplete="off" class="col-xs-12 no-padding">          
              <input class="icon-option ico-guest" type="submit" name="anonSubmit" id="anonSubmit" value="">
              <p>Invitado</p>
            </form>
          </div>
        </div>      
      </div>
    </div>

<!-- Modal INGRESAR PIN-->
<div class="modal fade" id="modalPin" tabindex="-1" role="dialog" aria-labelledby="modalPinLabel">
  <div class="modal-dialog" role="document">
    <div class=" contenedor-formulario">
    <form id="pinAuthForm" name="pinAuthForm" method="post" autoComplete="off" class="formulario">
      <div class="modal-content">
        <div class="modal-header text-center">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="modalPinLabel">INGRESA TU ID</h4>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-md-offset-2 col-md-8 col-xs-12">
            <div class="input-group">
              <input class="teclado inputKiosco form-control" type="password" name="pinNum" id="pinNum" onkeyup="keyUpSpeed()" autoComplete="off" maxlength="100">
              <label class="label" for="pinNum" required="" autoComplete="off">PIN</label>
            </div>
              <!-- <input class="teclado inputKiosco form-control" type="password" name="pinNum" id="pinNum" onkeyup="keyUpSpeed()" autoComplete="off" maxlength="100"> -->
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <div class="row">
            <div class="col-xs-6">
              <button type="button"  data-dismiss="modal" class="btn btn-danger pull-left">CANCELAR</button>
            </div>
            <div class="col-xs-6">
              <button type="submit" class="btn btn-success">INGRESAR</button>
            </div>
          </div>
        </div>
      </div>
    </form>
    </div>
  </div>
</div>

  <!-- Modal TARJETA-->
<div class="modal fade" id="modalTarjeta" tabindex="-1" role="dialog" aria-labelledby="modalTarjetaLabel">
  <div class="modal-dialog" role="document">
    <form id="pinAuthForm" method="post" autoComplete="off">
      <div class="modal-content">
        <div class="modal-header text-center">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="modalTarjetaLabel">DESLIZA TU TARJETA</h4>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-xs-12 text-center">
              Por favor, desliza tu tarjeta por el lector.
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

<!-- Modal INGRESAR PIN-->
<div class="modal fade" id="modalUsuario" tabindex="-1" role="dialog" aria-labelledby="modalUsuarioLabel">
  <div class="modal-dialog" role="document">
    <div class="contenedor-formulario">
    <form id="login" action="<?= $loginuserpassword ?>" name="userlogin" method="post" autoComplete="off">
      <div class="modal-content">
        <div class="modal-header text-center">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="modalUsuarioLabel">USUARIO</h4>
        </div>
        <div class="modal-body">
          <!--  -->
          <div class="row">
            <div class="col-md-offset-2 col-md-8 col-xs-12 pt-20">

              <div class="input-group">
                <input type="text" id="username" name="username" class="" onkeyup="keyUpSpeed()" autocomplete="off">
                <label class="label" for="username">Usuario</label>
              </div>
              <div class="input-group">
                <input type="password" id="password" name="password" class="" onkeyup="keyUpSpeed()" autocomplete="off">
                <label class="label" for="password">Contraseña</label>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <div class="row">
            <div class="col-xs-12">
              <button type="button"  data-dismiss="modal" class="btn btn-danger pull-left">CANCELAR</button>
              <input class=" btn btn-success" type="submit" name="userpassSubmit" id="userpassSubmit" value="ENTRAR">
            </div>
          </div>
        </div>
      </div>
    </form>
    </div>
  </div>
</div>

  <!-- ENTRAR Y SALIR -->
  <div id="entrarSalirLogin" style="display: none;">
    <form action="<?= $loginandrelease ?>" id="loginreleaseform" method="post" autoComplete="off"></form>
  </div>

  <!-- FORM MODALES -->
  <form id="pinsubmit" method="post" autocomplete="false">
    <div class="modal fade" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" id="pinmodal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" id="gridSystemModalLabel">Ingresa tu pin</h4>
          </div>
          <div class="modal-body">
            <input type="password" style="max-width: 69%; margin: auto;" maxlength="20" class="teclado pin form-control" name="pinInput" id="pinInput" autoComplete="off" autofocus>
          </div> 
          <div class="modal-footer">
            <input type="submit" class="btn btn-success btn-enviarModal" id="btnPinSubmit" name="btnPinSubmit" value="Entrar">
            <input type="button" class="btn btn-default pull-left" id="btnCancelarPin" name="btnCancelarPin" value="Cancelar">
          </div>
        </div>
      </div>
    </div>
  </form>

  <form id="asociarpinsubmit" method="post" autoComplete="off">
    <div class="modal fade" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" id="asociarpinmodal">
      <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" id="gridSystemModalLabel">Ingresa tu nuevo pin</h4>
          </div>
          <div class="modal-body">
              <input type="password" style="max-width: 69%; margin: auto;" class="teclado pin form-control" maxlength="20" name="newPinInput" id="newPinInput" autoComplete="off" autofocus>
          </div>
          <div class="modal-footer">
            <input class="btn btn-success btn-enviarModal btn-sm" type="submit" id="btnAsociarPin" name="btnAsociarPin" value="Enviar">
            <input class="btn btn-default btn-sm pull-left" type="button" id="btnCancelarAsociar" name="btnCancelarAsociar" value="Cancelar">
          </div>
        </div>
      </div>
    </div>
  </form>

  <!-- VENTANAS MODALES -->

<div class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false" role="dialog" id="userpassmodal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      </div>
      <div class="modal-body">
        <p><span class="glyphicon glyphicon-user"></span><b>&nbsp;&nbsp;Usuario o contraseña inválidos. Por favor, intente nuevamente</b></p>
      </div> 
      <div class="modal-footer">
        <button type="button" class="btn btn-success btn-enviarModal" data-dismiss="modal" id="btnUserPassError" name="btnUserPassError">Aceptar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" id="modalAnonUser">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      </div>
      <div class="modal-body">
        <p><span class="glyphicon glyphicon-credit-card"></span><b>&nbsp;Usuario invitado no ha sido creado. Contacte al administrador</b></p>
      </div> 
      <div class="modal-footer">
        <button type="button" class="btn btn-enviarModal btn-success" data-dismiss="modal" id="btnUserAnonError" name="btnUserAnonError">Aceptar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


 <div class="modal fade" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" id="numCardIncorrecto">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      </div>
      <div class="modal-body">
        <p><span class="glyphicon glyphicon-credit-card"></span><b>&nbsp;Número de tarjeta incorrecto. Intenta nuevamente</b></p>
      </div> 
      <div class="modal-footer">
        <button type="button" class="btn btn-enviarModal btn-success" id="numCardIncorrectoBtn" data-dismiss="modal">Aceptar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false"role="dialog" id="enrolarModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      </div>
      <div class="modal-body">
        <p><span class="glyphicon glyphicon-credit-card"></span><b>&nbsp;Número de tarjeta no registeado. ¿Desea enrolar?</b></p>
      </div> 
      <div class="modal-footer">
      <input type="button" class="btn btn-enviarModal btn-success" id="enrolarAceptarBtn" name="enrolarAceptarBtn" data-dismiss="modal" value="Aceptar">
        <button type="button" class="btn btn-default pull-left" id="enrolarCancelarBtn" data-dismiss="modal">Cancelar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" id="pinincorrecto">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      </div>
      <div class="modal-body">
        <p><span class="glyphicon glyphicon-user"></span><b>&nbsp;&nbsp; Pin incorrecto. Intente nuevamente</b></p>
      </div> 
      <div class="modal-footer">
        <button type="button" class="btn btn-enviarModal btn-success" data-dismiss="modal" id="btnAceptarError2">Aceptar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" id="validarpinmodal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      </div>
      <div class="modal-body">
        <p><span class="glyphicon glyphicon-user"></span><b>&nbsp;&nbsp; Pin incorrecto. Ingrese mínimo 4 digitos numéricos.</b></p>
      </div> 
      <div class="modal-footer">
        <button type="button" class="btn btn-enviarModal btn-success" data-dismiss="modal" id="btnAceptarError1">Aceptar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" id="asociarpin">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      </div>
      <div class="modal-body">
        <p><span class="glyphicon glyphicon-exclamation-sign"></span><b>&nbsp;&nbsp; Se requiere un pin para ingresar. ¿Desea crearlo?</b></p>
      </div> 
      <div class="modal-footer">
        <button type="button" class="btn btn-success btn-enviarModal" id="btnaceptarasociacionpin" data-dismiss="modal">Aceptar</button>
        <button type="button" class="btn btn-default pull-left" id="btncancelarasociacionpin" data-dismiss="modal">Cancelar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" id="sinpin">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      </div>
      <div class="modal-body">
        <p><span class="glyphicon glyphicon-exclamation-sign"></span><b>&nbsp;&nbsp; Usted no posee un pin asociado a su número de tarjeta. Por favor, contacte a su administrador</b></p>
      </div> 
      <div class="modal-footer">
        <button type="button" class="btn btn-success btn-enviarModal" id="btnNoPin" data-dismiss="modal">Aceptar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" id="ajaxerror">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      </div>
      <div class="modal-body">
        <p><span class="glyphicon glyphicon-exclamation-sign"></span><b>&nbsp;&nbsp; Ha fallado la conexión. Intente nuevamente</b></p>
      </div> 
      <div class="modal-footer">
        <button type="button" class="btn btn-success btn-enviarModal" id="btnAjaxErrorOk" name="btnAjaxErrorOk" data-dismiss="modal">Aceptar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false" role="dialog" id="pinasociadoexitomodal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      </div>
      <div class="modal-body">
        <p><span class="glyphicon glyphicon-exclamation-sign"></span><b>&nbsp;&nbsp; Se ha asociado su pin exitosamente</b></p>
      </div> 
      <div class="modal-footer">
        <button type="button" class="btn btn-success btn-enviarModal" data-dismiss="modal" id="btnAsociado">Aceptar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false" role="dialog" id="pinasociadofailmodal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      </div>
      <div class="modal-body">
        <p><span class="glyphicon glyphicon-exclamation-sign"></span><b>&nbsp;&nbsp; Ha fallado la asociación de pin. Intente nuevamente</b></p>
      </div> 
      <div class="modal-footer">
        <button type="button" class="btn btn-success btn-enviarModal" id="btnAsociarPinError" data-dismiss="modal">Aceptar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" id="jobnotfoundloginrelease">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      </div>
      <div class="modal-body">
        <p><span class="glyphicon glyphicon-user"></span><b>&nbsp;&nbsp; No se han encontrado trabajos cargados a su cuenta</b></p>
      </div> 
      <div class="modal-footer">
        <button type="button" class="btn btn-enviarModal btn-success" id="btnjobnotfoundloginrelease" name="btnjobnotfoundloginrelease" data-dismiss="modal">Aceptar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false" role="dialog" id="barraProgreso">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header" style="border-bottom: 1px solid #fff;">
      </div>
        <div style="width: 82%; margin: auto;">
          <div class="progress" style="height: 31px;">
            <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:100%">
              <h5><b><p id="cantTrabajos"></p></b></h5>
            </div>
          </div>
        </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false" role="dialog" id="notEnoughCredit">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      </div>
      <div class="modal-body">
        <p><span class="glyphicon glyphicon-user"></span><b>&nbsp;&nbsp; Saldo insufiencie</b></p>
      </div> 
      <div class="modal-footer">
        <button type="button" class="btn btn-enviarModal btn-success" id="btnSaldoInsu" name="btnSaldoInsu" data-dismiss="modal">Aceptar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


  <script type="text/javascript">

  $(function(){
    $("#cardNo").focus();
  });

    function userPassErrorMsg()
    {
       document.getElementById("modalUsuarioLabel").innerHTML = "Usuario o contraseña inválidos. Por favor, intente nuevamente";
       $('#modalUsuarioLabel').css('color', '#c0392b');
    }

    function numIDErrorMsg()
    {
       document.getElementById("modalPinLabel").innerHTML = "Número de ID incorrecto. Intenta nuevamente";
       $('#modalPinLabel').css('color', '#c0392b');
    }

    function limpiarMensajesError()
    {
       document.getElementById("modalUsuarioLabel").innerHTML = "USUARIO";
       $('#modalUsuarioLabel').css('color', '#000');

       document.getElementById("modalPinLabel").innerHTML = "INGRESA TU ID";
       $('#modalPinLabel').css('color', '#000');
    }

    var pinLogin = '<?php echo $usePinAuthentication ?>';
    var tarjetaLogin = '<?php echo $cardAuth ?>';
    var usuarioLogin = '<?php echo $usernameAuth ?>';
    var entrarSalirLogin = '<?php echo $enableLoginAndRelease ?>';
    var anonimoLogin = '<?php echo $anonLogin ?>';
    var releasePrinterError = '<?php echo $releasePrinterError ?>';

    var enableCardSelfAssociation = '<?php echo $enableCardSelfAssociation ?>';
    var cardSelfRegistration = '<?php echo $cardSelfRegistration ?>';
    var pinSelfAssociation = '<?php echo $pinSelfAssociation ?>';
    var selfUserAdjustBalance = '<?php echo $selfUserAdjustBalance ?>';

    var enableKeyboardAlways = '<?php echo $enableKeyboardAlways ?>';
    var enableKeyboard = '<?php echo $enableKeyboard ?>';
    
    var mostrarPinLogin = (pinLogin == "Y" ? $('#pinLogin').show():$('#pinLogin').hide());
    var mostrarTarjetaLogin = (tarjetaLogin == "Y" ? $('#tarjetaLogin').show():$('#tarjetaLogin').hide());
    var mostrarUsuarioLogin = (usuarioLogin == "Y" ? $('#usuarioLogin').show():$('#usuarioLogin').hide());
    var mostrarEntrarSalirLogin = (entrarSalirLogin == "Y" ? $('#entrarSalirLogin').show():$('#entrarSalirLogin').hide());
    var mostrarAnonimoLogin = (anonimoLogin == "Y" ? $('#anonimoLogin').show():$('#anonimoLogin').hide());


    //Error impresora
    if(releasePrinterError == "N")
    {
      if('<?php echo $printerStatus ?>' == "HABILITADA")
        {
          $('#alertPrinter').hide();
        }else if('<?php echo $printerStatus ?>' == "DESHABILITADA"){
          $('#alertPrinter').show();
          $('#printerStatusAlert').text("Hay problemas con la impresora, por favor, diríjase a otro kiosco. Estado: DESHABILITADA");
        }else if('<?php echo $printerStatus ?>' == "PAPEL ATASCADO"){
          $('#alertPrinter').show();
          $('#printerStatusAlert').text("Hay problemas con la impresora, por favor, diríjase a otro kiosco. Estado: PAPEL ATASCADO");
        }else if('<?php echo $printerStatus ?>' == "ERROR"){
          $('#alertPrinter').show();
          $('#printerStatusAlert').text("Hay problemas con la impresora, por favor, diríjase a otro kiosco. Estado: ERROR");
        }else if('<?php echo $printerStatus ?>' == "SIN CONEXIÓN"){
          $('#alertPrinter').show();
          $('#printerStatusAlert').text("Hay problemas con la impresora, por favor, diríjase a otro kiosco. Estado: SIN CONEXIÓN");
        }else if('<?php echo $printerStatus ?>' == "PAPEL ESCASO"){
          $('#alertPrinter').show();
          $('#printerStatusAlert').text("Hay problemas con la impresora, por favor, diríjase a otro kiosco. Estado: PAPEL ESCASO");
        }
    }

    var msgEnrolar = "Enrolarte";
    var msgRegistrar = "Registrarte";
    var msgAsociarPin = "Asociar tu N° PIN";
    var msgEntrarLi = "Entrar y liberar";
    var msgCargar = "Cargar saldo";

    //Mensaje funciones
    (enableCardSelfAssociation == "primary" || enableCardSelfAssociation == "secondary" ? msgEnrolar="- Enrolarte":msgEnrolar="");
    (cardSelfRegistration == "Y" ? msgRegistrar="Registrarte":msgRegistrar="- Registrarte");
    (pinSelfAssociation == "Y" ? msgAsociarPin="- Asociar tu N° PIN":msgAsociarPin="");
    (selfUserAdjustBalance == "Y" ? msgCargar="- Cargar saldo":msgCargar="");

    document.getElementById("mensajeFunciones").innerHTML = "<strong>En este kiosco podrás:</strong>  "+msgEnrolar+" "+msgRegistrar+" "+msgAsociarPin+" "+msgCargar+".";

    //ON CLICK

    $('body').on('click', function(){

    if($("#pinNum").is(":focus") || $("#password").is(":focus") || $("#username").is(":focus") || $("#entrar").is(":focus") || $("#visita").is(":focus") || $("#newPinInput").is(":focus"))
      {
        //alert("input");
      }else{
        $("#cardNo").focus();
        //alert($("#cardNo").is(":focus"));
      }
    });

    $('#btnCancelarPin').on('click', function(){
      $("#cardNo").val("");
      $('#pinmodal').modal('hide');
      $(function(){
            $("#cardNo").focus();
        });
    });

      $('#btnUserAnonError').on('click', function (e){
      $('#cardNo').val('');
      $(function(){
          $("#cardNo").focus();
      });
    });

  $('#btnUserPassError').on('click', function (e){
      $('#cardNo').val('');
      $('#password').val('');
      $('#username').val('');
      $(function(){
          $("#cardNo").focus();
      });
    });

  $('#aceptarModalUserPass').on('click', function (e){
      $('#cardNo').val('');
      $(function(){
          $("#cardNo").focus();
      });
    });

     $('#btncancelarasociacionpin').on('click', function (e){
      $('#cardNo').val('');
      $("#cardNo").focus();
    });


     $('#btnaceptarasociacionpin').on('click', function (e){
      $('#asociarpin').modal('hide');
      $('#asociarpinmodal').modal('show');

      $(function(){
          $("#cardNo").focus();
      });
    });

  $('#btnCancelarAsociar').on('click', function(){
    $("#cardNo").val("");
    $('#asociarpinmodal').modal('hide');
    $('#newPinInput').val("");
    $(function(){
          $("#cardNo").focus();
      });
  });

  $('#btnPinSubmit').click(function(){
    $('#pinmodal').modal('hide');
    $(function(){
        $("#cardNo").focus();
    });
  });

    $('#btnAceptarError1, #btnAceptarError2, #btnAsociado, #numCardIncorrectoBtn').on('click', function(){
      limpiarCampos();

      $(function(){
            $("#cardNo").focus();
        });
    });

  $('#enrolarAceptarBtn').on('click', function (e){
    $('#cardNo').val("");
    window.location.href = '<?php echo $urlEnrolar."/".$kiosco ?>';
  });
  $('#enrolarCancelarBtn').on('click', function (e){
    $('#cardNo').val("");
    $('#pinNum').val("");
    $('#enrolarModal').modal('hide');
    $(function(){
        $("#cardNo").focus();
    });
  });

    $('#btnAsociarPinError').on('click', function(){
        $(function(){
              $("#cardNo").focus();
          });
      });

    $("#newPinInput").on('click', function(){
          document.getElementById("newPinInput").focus();
          $('#newPinInput').focus();
    });

    $('#btnAceptarError1').on('click', function(){
      $(function(){
            $("#cardNo").focus();
        });
    });

    $('#btnSaldoInsu').on('click', function(){
      $(function(){
            $("#cardNo").focus();
        });
    });

    $('#btnAjaxErrorOk').on('click', function(){
      $(function(){
            $("#cardNo").focus();
        });
    });

    $('#btnNoPin').on('click', function(){
      $(function(){
            $("#cardNo").focus();
        });
    });

    $('#btnAsociarPin').on('click', function(){
      $(function(){
            $("#cardNo").focus();
        });
    });

    $('#btnaceptarasociacionpin').on('click', function(){
      $(function(){
            $("#cardNo").focus();
        });
    });

      $('#newPinInput').on('click', function(){
    $(function(){
          $("#cardNo").focus();
      });
  });

      $('#userpassmodal').on('click', function(){
    $(function(){
          $("#cardNo").focus();
      });
  });

    $('#btnUserAnonError').on('click', function(){
    $(function(){
          $("#cardNo").focus();
      });
  });

    $('#btnAceptarError2').on('click', function(){
    $(function(){
          $("#cardNo").focus();
      });
  });

    $('#btnjobnotfoundloginrelease').on('click', function(){
    $(function(){
          $("#cardNo").focus();
      });
  });

  $('#enrolarAceptarBtn').on('click', function(){
    $(function(){
          $("#cardNo").focus();
      });
  });

  $('#btnAsociado').on('click', function(){
    $(function(){
          $("#cardNo").focus();
      });
  });

  $('#pinInput').on('click', function(){
    $(function(){
          $("#cardNo").focus();
      });
  });

    $('#numCardIncorrectoBtn').on('click', function(){
    $(function(){
          $("#cardNo").focus();
      });
  });

  // FOCUS MODALES

  $('#modalTarjeta, #modalUsuario, #modalPin').on('shown.bs.modal', function () {
    limpiarMensajesError();
      $(function(){
          $("#cardNo").focus();
      });
  });

  $('#modalTarjeta, #modalUsuario, #modalPin').on('hide.bs.modal', function () {
    limpiarMensajesError();
      $(function(){
          $("#cardNo").focus();
      });
  });

  $('#modalTarjeta, #modalUsuario, #modalPin').on('hidden.bs.modal', function () {
      $(function(){
          $("#cardNo").focus();
      });
  });


  $('#validarpinmodal').on('shown.bs.modal', function () {
      $('#btnAceptarError1').focus();
  });

  $('#notEnoughCredit').on('shown.bs.modal', function () {
      $('#btnSaldoInsu').focus();
  });

  $('#ajaxerror').on('shown.bs.modal', function () {
      $('#btnAjaxErrorOk').focus();
  });

  $('#sinpin').on('shown.bs.modal', function () {
      $('#btnNoPin').focus();
  });

  $('#asociarpin').on('shown.bs.modal', function () {
      $('#btnaceptarasociacionpin').focus();
  });

  $('#asociarpinmodal').on('shown.bs.modal', function () {
      $('#btnAsociarPin').focus();
  });

  $('#pinasociadoexitomodal').on('shown.bs.modal', function () {
      $('#btnAsociado').focus();
  });

  $('#enrolarModal').on('shown.bs.modal', function () {
      $('#enrolarAceptarBtn').focus();
  });

  $('#jobnotfoundloginrelease').on('shown.bs.modal', function () {
      $('#btnjobnotfoundloginrelease').focus();
  });

  $('#barraProgreso').on('shown.bs.modal', function () {
      $('#cardNo').focus();
  });

  $('#pinincorrecto').on('shown.bs.modal', function () {
      $('#btnAceptarError2').focus();
  });

  $('#modalAnonUser').on('shown.bs.modal', function () {
      $('#btnUserAnonError').focus();
  });

  $('#userpassmodal').on('shown.bs.modal', function () {
      $('#btnUserPassError').focus();
  });

  $('#numCardIncorrecto').on('shown.bs.modal', function () {
      $('#numCardIncorrectoBtn').focus();
  });

  $('#asociarpinmodal').on('shown.bs.modal', function () {
      $('#newPinInput').focus();
  });

  $('#pinmodal').on('shown.bs.modal', function () {
      $('#pinInput').focus();
  });

  $('#pinasociadofailmodal').on('shown.bs.modal', function () {
      $('#btnAsociarPinError').focus();
  });

  function limpiarCampos()
  {
    $('#username').val('');
    $('#password').val('');
    $('#cardNo').val('');
    $('#pinInput').val('');
    $('#pinNum').val('');

    $('#username').css( "border-color", "#ccc" );
    $('#password').css( "border-color", "#ccc" );
  }

  $('#pinAuthForm').on('submit', function (e){
    e.preventDefault();
    $.ajax({
      url: '<?php echo $pinNum ?>',
      type: 'POST', 
      data: $("#pinAuthForm").serialize(),
      dataType: 'json', 
      timeout: 10000,
      success: function(pinData) {

        var who = typingSpeed("pinNum");

        if(who == "persona" || !who)
        {
          if(pinData.respuesta == true)
          {
            if(pinData.enableLoginAndRelease == "N")
            {
              window.location.href = '<?php echo $liberador."/".$kiosco ?>';
              
            }else{
              $("#loginreleaseform").submit();

              $(function(){
                  $("#cardNo").focus();
              });

              limpiarCampos();
            }
          }else{
            numIDErrorMsg();
          }
        }else{
          $('#cardNo').focus();
        }

        limpiarCampos();

    },
    error: function(xhr, textStatus, errorThrown){
       $('#ajaxerror').modal('show');
       limpiarCampos();
    }
  });
});

  $('#cardForm').on('submit', function (e){
    
    e.preventDefault();
    $.ajax({
      url: '<?php echo $urlCardNo ?>',
      type: 'POST', 
      data: $("#cardForm").serialize(),
      dataType: 'json', 
      timeout: 10000,
      success: function(cardnodata) {
        var who = typingSpeed("cardNo");
        
        if(who == "lector")
        {
            console.log(cardnodata);
            if(cardnodata.respuesta == "empty_card_number")
            {
              $('cardNo').focus();
            }else if(cardnodata.respuesta == 'userwithoutpin')
            {
             $('#sinpin').modal('show');
            }else if(cardnodata.respuesta == 'userwithpin'){
              $('#pinmodal').modal('show');
            }else if(cardnodata.respuesta == 'enrolar'){
              $('#enrolarModal').modal('show');
            }else if(cardnodata.respuesta == "noenrolar"){
              $('#numCardIncorrecto').modal('show');
              
                $('#cardNo').val("");
            }else if(cardnodata.respuesta == 'nopin'){
              if(cardnodata.enableLoginAndRelease == "Y")
              {
                $("#loginreleaseform").submit();
                $(function(){
                    $("#cardNo").focus();
                });
              }else{
                window.location.href = '<?php echo $liberador."/".$kiosco ?>';
              }
            }else if(cardnodata.respuesta == "asociarpin"){
              $('#asociarpin').modal('show');
            }else if(cardnodata.respuesta = "errordeconexion"){
              $('#ajaxerror').modal('show');
              limpiarCampos();
            }
        }else{
          limpiarCampos();
          $('#cardNo').focus();
        }

        limpiarCampos();

    },
    error: function(xhr, textStatus, errorThrown){
       $('#ajaxerror').modal('show');
       limpiarCampos();
    }
  });
});

   $('#asociarpinsubmit').on('submit', function (e){
    e.preventDefault();
    var pin = $('#newPinInput').val();
    $.ajax({
      url: '<?php echo $asociar ?>',
      type: 'POST', 
      data: $("#asociarpinsubmit").serialize(), 
      dataType: 'json', 
      timeout: 5000,
      success: function(userPin) {
        console.log(userPin);
        if(userPin.respuesta=="pinasociado"){
          $('#pinasociadoexitomodal').modal('show');
          $('#asociarpinmodal').modal('hide');
          $('#cardNo').val('');
          $('#newPinInput').val('');
          $(function(){
              $("#cardNo").focus();
          });
        }else if(userPin.respuesta=="pinnoasociado"){
          $('#pinasociadofailmodal').modal('show');
          $('#asociarpinmodal').modal('hide');
          $('#cardNo').val('');
          $('#newPinInput').val('');
          $(function(){
              $("#cardNo").focus();
          });
        }else if(userPin.respuesta=="errorpin")
        {
          $('#validarpinmodal').modal('show');
          $('#asociarpinmodal').modal('hide');
          $('#newPinInput').val('');
          $(function(){
              $("#cardNo").focus();
          });
        }
    },
    error: function(xhr, textStatus, errorThrown){
       $('#ajaxerror').modal('show');
       limpiarCampos();

    }
  });
});

   $('#pinsubmit').on('submit', function (e){
    e.preventDefault();
    var pin = $('#pinInput').val();
    $.ajax({
      url: '<?php echo $validarPin ?>',
      type: 'POST', 
      data: $("#cardForm").serialize(), 
      dataType: 'json', 
      timeout: 5000,
      success: function(userPin) {
        if(userPin.respuesta == pin){
          if(userPin.enableLoginAndRelease == "Y")
          {
            $("#loginreleaseform").submit();
            $(function(){
              $("#cardNo").focus();
          });
          }else{
            window.location.href = '<?php echo $liberador."/".$kiosco ?>';
          }
        }else if(pin.match(/[a-z]/i)){
          $('#validarpinmodal').modal('show');
          $('#pinInput').val('');
          $('#cardNo').val('');
        }else{
          $('#pinmodal').modal('hide');
          $('#pinincorrecto').modal('show');
          $('#pinInput').val('');
          $('#cardNo').val('');
        }
    },
    error: function(xhr, textStatus, errorThrown){
       $('#ajaxerror').modal('show');
       limpiarCampos();
    }
  });
});

   var enableLoginAndRelease = '<?php echo $enableLoginAndRelease ?>';

   $('#login').on('submit', function (e){
    e.preventDefault();
    $.ajax({
      url: '<?php echo $loginuserpassword ?>',
      type: 'POST', 
      data: $("#login").serialize(),
      dataType: 'json', 
      timeout: 3000,
      success: function(data) {

        if($('#username').val() == "" && $('#password').val() == "" || data.respuesta == "login_fail"){
            userPassErrorMsg();

            $('#cardNo').focus();
            limpiarCampos();
        }else if($('#username').val() == "" && $('#password').val() != ""){
          var who = typingSpeed("password");

          if(who == "persona")
          {
            $('#username').css( "border-color", "red" );
            $('#username').focus();
          }
   
          //limpiarCampos();
        }else if($('#username').val() != "" && $('#password').val() == ""){
          var who = typingSpeed("username");

          if(who == "persona")
          {
            $('#password').css( "border-color", "red" );
            $('#password').focus();
          }
              //limpiarCampos();
        }else{

          $('#username').css( "border-color", "#ccc" );
          $('#password').css( "border-color", "#ccc" );
          limpiarCampos();

        }

        console.log(data);
        
        if(data.autentificadoAdmin == true)
        {
          window.location.href = '<?php echo $panelcontrol ?>';
        }else if(data.autentificado == true)
        {
          
          if(enableLoginAndRelease == "Y")
          {
            $("#loginreleaseform").submit();

          }else{
            window.location.href = '<?php echo $liberador."/".urlencode($kiosco) ?>';
          }
          
        }else{
          userPassErrorMsg();
        }
    },
    error: function(xhr, textStatus, errorThrown){
       $('#ajaxerror').modal('show');
       limpiarCampos();
       
    }
  });
});

   $('#loginreleaseform').on('submit', function (e){
      e.preventDefault();
      $.ajax({
        url: '<?php echo $loginandrelease ?>',
        type: 'POST', 
        data: $("#loginreleaseform").serialize(),
        dataType: 'json', 
        timeout: 3000,
        success: function(data) {

          console.log(data)
        
        if(data.trabajos.length == 1)
        {
          document.getElementById("cantTrabajos").innerHTML = "Imprimiendo 1 trabajo";
        }else{
          document.getElementById("cantTrabajos").innerHTML = "Imprimiendo "+data.trabajos.length+" trabajos";
        }

        if(data.respuesta == "jobnotfound" || data.respuesta == "papercutjobnotfound")
        {
          $('#jobnotfoundloginrelease').modal('show');
          limpiarCampos();
        }else if(data.respuesta == "Success")
        {
          $('#barraProgreso').modal('show');
           setTimeout(function(){
            $('#barraProgreso').modal('hide');
           }, 5000);

          limpiarCampos();
        }else if(data.respuesta = "NotEnoughCredit")
        {
          $('#notEnoughCredit').modal('show');
          limpiarCampos();
        }
        $(function(){
            $("#cardNo").focus();
        });

        limpiarCampos();
      },
      error: function(xhr, textStatus, errorThrown){
         $('#ajaxerror').modal('show');
         limpiarCampos();
      }
    });
});

   $('#guessForm').on('submit', function (e){
    e.preventDefault();
    $.ajax({
      url: '<?php echo $guess ?>',
      type: 'POST', 
      data: $("#guessForm").serialize(),
      dataType: 'json', 
      timeout: 10000,
      success: function(anonUser) {
        console.log(anonUser);
        if(anonUser.enableLoginAndRelease == "Y")
        {
          if(anonUser.respuesta == "userExistsTrue")
          {
            $("#loginreleaseform").submit();

          }else if (anonUser.respuesta == "userExistsFalse"){
            $('#modalAnonUser').modal('show');
          }
        }else{
          if(anonUser.respuesta == "userExistsTrue")
          {
            window.location.href = '<?php echo $liberador."/".$kiosco ?>';

          }else if (anonUser.respuesta == "userExistsFalse"){
            $('#modalAnonUser').modal('show');
          }
        }

        limpiarCampos();
    },
    error: function(xhr, textStatus, errorThrown){
       $('#ajaxerror').modal('show');
       limpiarCampos();
    }
  });
});

$('#cardNo').focus();

    var typingMs = '<?php echo $typingSpeedMs ?>';
    var lengthNum = '<?php echo $lengthCardNumber ?>';
    var who = "";

    lengthCardNum = 0;
    time_start = 0;
    time_end = 0;

        function keyUpSpeed()
        {
          lengthCardNum++;

            if(lengthCardNum == 1)
            {
              time_start = new Date();
            }else{
              time_end = new Date().getTime() - time_start;
            }   
        }

          var delay = (function(){
           var timer = 0;
           return function(callback, ms){
              clearTimeout (timer);
              timer = setTimeout(callback, ms);
           };
        })();

        $("#pinNum, #username, #password, #cardNo").on("input", function() {
           delay(function(){

              if (lengthCardNum>=lengthNum && time_end <= typingMs) {
                who = "lector";
                //$("#username").attr('type', 'password');
                  
              }else{
                who = "persona";
                $("#username").attr('type', 'text');
              }
           }, 20 );
        });


    function typingSpeed(inputName)
    {
        if(who == "lector" && !$("#cardNo").is(":focus"))
        {
          var num = document.getElementById(inputName).value;
          document.getElementById("cardNo").value = num;

          var input = document.getElementById("cardNo").value;

          if(input.length == lengthNum)
          {
            $('#cardNo').focus();
            $('#cardForm').submit();
          }

          limpiarCampos();
        }

        lengthCardNum = 0;
        time_start = 0;
        time_end = 0;

        return who;
    }

  if(enableKeyboardAlways == "Y")
  {

  }else if (enableKeyboard == "N" && enableKeyboardAlways == "N")
  {
    $(".teclado").removeClass("teclado");
    $(".pinTeclado").removeClass("pinTeclado");

  }else if(enableKeyboard == "Y")
  {
    //$(".pin").addClass("pinTeclado");
    

  }else{
    //$(".pin").addClass("pinTeclado");
  }

  if(isMobile.any())
    {
      $(".teclado").removeClass("teclado");
      $(".pinTeclado").removeClass("pinTeclado");
    }


// Proporcionar circulos login

$( ".icon-option" ).each(function(i) {
  var hCircle = $(this).height();
  var wCircle = $(this).width();
  
  if(hCircle < wCircle){
    $(this).width(hCircle);  
  }else{
    $(this).height(wCircle);
  }  
  console.log(i+1+$(this).attr('class'));
});


// Funciones para diseño de formulario
(function() {
  var formulario = document.userlogin,
    elementos = formulario.elements;
  var focusInput = function() {
    this.parentElement.children[1].className = "label active";
    this.parentElement.children[0].className = this.parentElement.children[0].className.replace("error", "");
  };
  var blurInput = function() {
    if (this.value <= 0) {
      this.parentElement.children[1].className = "label";
      this.parentElement.children[0].className = this.parentElement.children[0].className + " error";
    }
  };
  
  // --- Eventos ---
  
  for (var i = 0; i < elementos.length; i++) {
    if (elementos[i].type == "text" || elementos[i].type == "email" || elementos[i].type == "password") {
      elementos[i].addEventListener("focus", focusInput);
      elementos[i].addEventListener("blur", blurInput);
    }
  }
}())
// Funciones para diseño de formulario
(function() {
  var formulario = document.pinAuthForm,
    elementos = formulario.elements;
  var focusInput = function() {
    this.parentElement.children[1].className = "label active";
    this.parentElement.children[0].className = this.parentElement.children[0].className.replace("error", "");
  };
  var blurInput = function() {
    if (this.value <= 0) {
      this.parentElement.children[1].className = "label";
      this.parentElement.children[0].className = this.parentElement.children[0].className + " error";
    }
  };
  // ---- EN CASO QUE ESTE AUTOCOMPLETADO ---
  $("form input[type='text'], form input[type='password']").val('');

  // --- Eventos ---
  
  for (var i = 0; i < elementos.length; i++) {
    if (elementos[i].type == "text" || elementos[i].type == "email" || elementos[i].type == "password") {
      elementos[i].addEventListener("focus", focusInput);
      elementos[i].addEventListener("blur", blurInput);
    }
  }
}())
</script>
</body>
</html>